<%@ Page Title="Please Suscribe" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Suscribe.aspx.cs" Inherits="Web_Form.Suscribe" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">


    <% 

        //create 2 constants for the min and max number of tickets (min1, min 5)

        // create 1 variable to hold the # of bought tickets

        /****************************************************************/

        //Response.Write("<div>" + productList() + "</div>");

        

        Response.Write("<div>" + productList(list) + "</div>");


        %>
    this is hard-coded text <br />

    <p><%Response.Write("This is generated by code!!! <br>"); %>
        
    </p>
    
    <asp:Button ID="Button1" runat="server" type="submit" name=" manualButton" Text="Button" />

    <% ="SHORTCUT" %>  <!-- Not recommended -->

    <%
        //write an if/else statement
        //if the # of bought tickets is between the min and max write: you bought 3 tickets
        // else write you can only purchase between 1 and 5 tickets


        Response.Write(showBoughtTickets());

        
        // create a div containing some text, and specify a style with CSS

        Response.Write("<div class='textDiv'><p class='mediumText'> this is a paragraph text</p></div>");

        Response.Write("<div class = \"mediumText textDiv\"> testing CSS styles</div>");

        Response.Write($"<br> the new number of tickets is {numTickets}");

        Response.Write($"<br> 100 + 500 = {addNumbers(100, 500)}");


    %>



   
</asp:Content>
